# Generated by Django 5.1.4 on 2024-12-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profes', '0002_profes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='app_profes'),
        ),
    ]
